/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TenantRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivateTenant"
      | "getTenantCount"
      | "getTenantInfo"
      | "getTenants"
      | "isTenant"
      | "owner"
      | "registerTenant"
      | "registrationFee"
      | "renounceOwnership"
      | "setRegistrationFee"
      | "tenants"
      | "transferOwnership"
      | "updateTenant"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "TenantDeactivated"
      | "TenantRegistered"
      | "TenantUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivateTenant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTenantCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTenantInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTenants",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTenant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerTenant",
    values: [string, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registrationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistrationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tenants",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTenant",
    values: [string, string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "deactivateTenant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTenantCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTenantInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTenants", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isTenant", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerTenant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registrationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegistrationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tenants", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTenant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TenantDeactivatedEvent {
  export type InputTuple = [tenant: AddressLike];
  export type OutputTuple = [tenant: string];
  export interface OutputObject {
    tenant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TenantRegisteredEvent {
  export type InputTuple = [tenant: AddressLike, name: string];
  export type OutputTuple = [tenant: string, name: string];
  export interface OutputObject {
    tenant: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TenantUpdatedEvent {
  export type InputTuple = [tenant: AddressLike];
  export type OutputTuple = [tenant: string];
  export interface OutputObject {
    tenant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TenantRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): TenantRegistry;
  waitForDeployment(): Promise<this>;

  interface: TenantRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivateTenant: TypedContractMethod<
    [tenant: AddressLike],
    [void],
    "nonpayable"
  >;

  getTenantCount: TypedContractMethod<[], [bigint], "view">;

  getTenantInfo: TypedContractMethod<
    [addr: AddressLike],
    [
      [string, string, string, boolean, bigint] & {
        name: string;
        metadata: string;
        feeRecipient: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  getTenants: TypedContractMethod<[], [string[]], "view">;

  isTenant: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerTenant: TypedContractMethod<
    [name: string, metadata: string, feeRecipient: AddressLike],
    [void],
    "payable"
  >;

  registrationFee: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setRegistrationFee: TypedContractMethod<
    [fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  tenants: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, boolean, bigint] & {
        name: string;
        metadata: string;
        feeRecipient: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateTenant: TypedContractMethod<
    [name: string, metadata: string, feeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivateTenant"
  ): TypedContractMethod<[tenant: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTenantCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTenantInfo"
  ): TypedContractMethod<
    [addr: AddressLike],
    [
      [string, string, string, boolean, bigint] & {
        name: string;
        metadata: string;
        feeRecipient: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTenants"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isTenant"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerTenant"
  ): TypedContractMethod<
    [name: string, metadata: string, feeRecipient: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "registrationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRegistrationFee"
  ): TypedContractMethod<[fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tenants"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, boolean, bigint] & {
        name: string;
        metadata: string;
        feeRecipient: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTenant"
  ): TypedContractMethod<
    [name: string, metadata: string, feeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TenantDeactivated"
  ): TypedContractEvent<
    TenantDeactivatedEvent.InputTuple,
    TenantDeactivatedEvent.OutputTuple,
    TenantDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "TenantRegistered"
  ): TypedContractEvent<
    TenantRegisteredEvent.InputTuple,
    TenantRegisteredEvent.OutputTuple,
    TenantRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "TenantUpdated"
  ): TypedContractEvent<
    TenantUpdatedEvent.InputTuple,
    TenantUpdatedEvent.OutputTuple,
    TenantUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TenantDeactivated(address)": TypedContractEvent<
      TenantDeactivatedEvent.InputTuple,
      TenantDeactivatedEvent.OutputTuple,
      TenantDeactivatedEvent.OutputObject
    >;
    TenantDeactivated: TypedContractEvent<
      TenantDeactivatedEvent.InputTuple,
      TenantDeactivatedEvent.OutputTuple,
      TenantDeactivatedEvent.OutputObject
    >;

    "TenantRegistered(address,string)": TypedContractEvent<
      TenantRegisteredEvent.InputTuple,
      TenantRegisteredEvent.OutputTuple,
      TenantRegisteredEvent.OutputObject
    >;
    TenantRegistered: TypedContractEvent<
      TenantRegisteredEvent.InputTuple,
      TenantRegisteredEvent.OutputTuple,
      TenantRegisteredEvent.OutputObject
    >;

    "TenantUpdated(address)": TypedContractEvent<
      TenantUpdatedEvent.InputTuple,
      TenantUpdatedEvent.OutputTuple,
      TenantUpdatedEvent.OutputObject
    >;
    TenantUpdated: TypedContractEvent<
      TenantUpdatedEvent.InputTuple,
      TenantUpdatedEvent.OutputTuple,
      TenantUpdatedEvent.OutputObject
    >;
  };
}
